version: '3.0'

services:
  backend:
    build:
      context: ./docker
      dockerfile: Dockerfile-php
    container_name: archive-manager_fpm
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - exchange
    environment:
      - RABBITMQ_HOST=exchange
      - RABBITMQ_PORT=5672

  frontend:
    image: nginx:latest
    container_name: archive-manager_frontend
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/var/www/

  exchange:
    image: rabbitmq:3.9-management-alpine
    container_name: archive-manager_rabbitmq
    ports:
      - 15672:15672
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf