FROM php:7.4-fpm

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y libonig-dev && \
    docker-php-ext-install -j$(nproc) iconv mbstring sockets json

CMD ["php-fpm"]
